formatter: "markdown"

# update module readmes
recursive:
  enabled: true
  path: modules

sections:
  hide:
    - resources
    - data-sources

settings:
  # extract provider versions from .tf rather than from your specific lockfile. without this, building
  # docs will vary between developers (and cicd), due to differing lockfiles
  lockfile: false

output:
  file: "README.md"
  # enrich README with module documentation, rather than overwriting the entire file
  mode: "inject"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
