name: Reusable Pre-Commit Job

# Reusable pre-commit workflow. Note this does not run automatically, it must be invoked by another workflow
on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Here we read the terraform version from the .terraform-version file, and then install that version
      - name: Get Terraform version
        id: tf_version
        run: |
          echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.value }}
      - uses: terraform-linters/setup-tflint@v6
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
